# Site settings
title: The Beast of Riverdale
author: Jeremy Jones
email: jeroum@gmail.com
description: ""
tagline: ""
baseurl: ""
url: ""
twitter_username: ""
github_username: ""
facebook_username: ""
timezone: America/New_York
modular_scale: http://www.modularscale.com/?1&em&1.333&web&text
text_skew_v: -8.0

# Soundcloud
soundcloud_ids:
  - 224147716

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
