# Site settings
title: Mint-Jekyll
author: Jeremy Jones
username: minttoothpick
email: jeroum@gmail.com
description: "Blog and internet home for Jeremy Jones."
tagline: "Brief tagline"
baseurl: ""
url: ""
twitter_username: minttoothpick
github_username:  minttoothpick
timezone: America/New_York

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
