# Site settings
title: The Beast of Riverdale
author: Jeremy Jones
email: jeroum@gmail.com
description: ""
tagline: ""
baseurl: ""
url: ""
twitter_username:
github_username:
timezone: America/New_York

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
